# The channels array will be automatically edited by the bot during run-time.
# I recommend only editing it when the bot is offline
channels:
imgur:
  client_id:
command_prefix: "!"
irc:
  server:
  port:
  ssl:
  nick:
  # An array of modes the bot sets on itself
  modes: 
  sasl:
    username:
    password:
watermark_prefix:
